dynamic list of todos
mate-academy/react_goods-selector-js pull request #1
Opened 2023-06-25 19:27 UTC by JasterHim

[DEMO LINK](https://JasterHim.github.io/react_goods-selector/)

2023-06-25 19:35 UTC, JasterHim commented
In the README.md file, the path to the DEMO LINK is incorrectly specified. Need to replace `https://<your_account>.github.io/react_goods-selector/` with `https://<your_account>.github.io/react_goods-selector-js/`

2023-06-26 07:32 UTC, etojeDenys requested changes

2023-06-26 07:32 UTC, etojeDenys commented on src/App.jsx
> +              </td>
if we change almost everything depends on condition `nameGood === good`
better to write:
```
{nameGood === good ? (
  <tr>... </tr>
) : (
   <tr> ... </tr>
)}
```

2023-06-26 09:57 UTC, VitaliyBondarenko1982 approved these changes

2023-11-20 06:15 UTC, closed without merging