Task is done
mate-academy/react_goods-selector-js pull request #110
Opened 2023-07-10 18:19 UTC by Konsttantin

[DEMO LINK](https://Konsttantin.github.io/react_goods-selector-js/)

2023-07-11 08:53 UTC, OleziO requested changes

2023-07-11 08:53 UTC, OleziO commented on src/App.jsx
> +  const [selectedGood, setGood] = useState('Jam');
Replace `'Jam'` with `goods[goods.indexOf('Jam')] || goods[0]`
Its more safe variant.

2023-07-11 08:53 UTC, OleziO commented on src/App.jsx
> +            <tr
Add key attr.

2023-07-12 10:22 UTC, demetrxx approved these changes
Well done 👍 Go ahead!

2025-01-19 15:39 UTC, closed without merging