solution
mate-academy/react_goods-selector-js pull request #1239
Opened 2024-11-29 19:28 UTC by HokageHEL

[DEMO LINK](https://hokagehel.github.io/react_goods-selector-js/)

2024-11-29 19:28 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **The test task has already been approved.**
> <sub>*[CODE: 9]*</sub>


If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-11-29 20:40 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **The test task has already been approved.**
> <sub>*[CODE: 9]*</sub>


If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-11-29 22:00 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **The test task has already been approved.**
> <sub>*[CODE: 9]*</sub>


If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-11-29 23:20 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **The test task has already been approved.**
> <sub>*[CODE: 9]*</sub>


If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-11-30 07:49 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-11-30 07:49 UTC, volodymyr-soltys97 commented on src/App.jsx
> +            onClick={() => setSelectedGood('')}
Create a helper function for reset logic and use it in two places

2024-11-30 07:49 UTC, volodymyr-soltys97 commented on src/App.jsx
> +                  'has-background-success-light': good === selectedGood,
Move this checking to the variable and use it everywhere
```suggestion
          {goods.map(good => {
            const isSelected = good === selectedGood;
            
            return (
              <tr
                data-cy="Good"
                className={cn({
                  'has-background-success-light': isSelected,
```

2024-11-30 09:05 UTC, etojeDenys approved these changes

2024-11-30 15:49 UTC, closed without merging