add task solution
mate-academy/react_goods-selector-js pull request #243
Opened 2023-08-24 16:28 UTC by Koliras

[DEMO LINK](https://Koliras.github.io/react_goods-selector-js/)

2023-08-24 20:39 UTC, AngerDESTROYS approved these changes
Gj

2023-08-29 06:48 UTC, Moroz-Dmytro requested changes

2023-08-29 06:48 UTC, Moroz-Dmytro commented on src/App.jsx
> +  const [product, setProduct] = useState('Jam');
```suggestion
  const [selectedGood, setSelectedGood] = useState('Jam');
```

2023-08-29 06:48 UTC, Moroz-Dmytro commented on src/App.jsx
> +        selected
Try to refactor this. If you have selected a product then show this info, otherwise just show "No goods selected message"

2023-08-29 06:48 UTC, Moroz-Dmytro commented on src/App.jsx
> +            onClick={() => setProduct(NO_GOODS_SELECTED)}
<img width="665" alt="image" src="https://github.com/mate-academy/react_goods-selector-js/assets/86789161/c274c870-1987-493f-8739-41832f23ff81">

2023-08-29 06:48 UTC, Moroz-Dmytro commented on src/App.jsx
> +                    })}
```suggestion
                    className={classNames('button', {
                      'is-info': isSelected,
                    })}
```
Read more [here](https://www.npmjs.com/package/classnames)

2023-08-29 06:48 UTC, Moroz-Dmytro commented on src/App.jsx
> +                      isSelected = !isSelected;
What are you doing here? Why you need this?

2023-08-29 06:48 UTC, Moroz-Dmytro commented on src/App.jsx
> +            let isSelected = product === good;
```suggestion
            const isSelected = product === good;
```

2023-08-29 06:48 UTC, Moroz-Dmytro commented on src/App.jsx
> +                      setProduct(product !== good
You can use `isSelected` here

2023-08-29 06:48 UTC, Moroz-Dmytro commented on src/App.jsx
> +                        : NO_GOODS_SELECTED);
When you unselect product -> you should just set the empty string to state.

2023-08-30 06:29 UTC, Moroz-Dmytro approved these changes

2023-08-30 06:29 UTC, Moroz-Dmytro commented on src/App.jsx
> +        {selectedGood !== '' && (
```suggestion
        {selectedGood && (
```

2024-12-16 14:48 UTC, closed without merging