Solution
mate-academy/react_goods-selector-js pull request #51
Opened 2023-06-30 20:02 UTC by eleonora-demikh

[DEMO LINK](https://eleonora-demikh.github.io/react_goods-selector-js/)

2023-07-02 12:06 UTC, MarianVolytskyi commented on src/App.jsx
> +            {`${selectedGood} is selected`}
you can add only text in h1 tag , because  <h1 className="title is-flex is-align-items-center">  is the same in both  tag

2023-07-02 12:08 UTC, MarianVolytskyi commented on src/App.jsx
> +                : ''}
you can use classnames library

2023-07-02 12:10 UTC, MarianVolytskyi approved these changes
Looks good)
Please read my comments)

2023-07-03 09:35 UTC, juljaVysotska requested changes
Good job! 
I found some issues, please check and fix them
Best regards

2023-07-04 06:37 UTC, mgrinko approved these changes

2023-07-04 06:37 UTC, mgrinko commented on src/App.jsx
> +                    ? (
```suggestion
                {selectedGood === good ? (
```

2023-07-04 06:37 UTC, mgrinko commented on src/App.jsx
> +                    : (
```suggestion
                    ) : (
```

2025-01-10 08:23 UTC, closed without merging