task done
mate-academy/react_goods-selector-js pull request #586
Opened 2024-01-07 19:51 UTC by Manankin

[DEMO LINK](https://Manankin.github.io/react_goods-selector-js/)

2024-01-09 12:48 UTC, olya-shyian requested changes
Cool!💫

2024-01-09 12:48 UTC, olya-shyian commented on src/App.jsx
> +  }
you can use just a const

`const isGoodSelected = good === selectedGood;`

create this const inside map function

2024-01-09 12:48 UTC, olya-shyian commented on src/App.jsx
> +        selectedGood !== '' ? (
you can write `{` and ` selectedGood !== '' ? (` on the same line

2024-01-09 12:48 UTC, olya-shyian commented on src/App.jsx
> +        selectedGood !== '' ? (
also instead just write `{selectedGood ? (`

2024-01-09 12:48 UTC, olya-shyian commented on src/App.jsx
> +                {selectedGood === good
replace with isGoodSelected const

2024-01-09 21:27 UTC, l0ad1nggg approved these changes
Good job!

2024-01-10 11:41 UTC, anstsot approved these changes
Good work, approving :sparkles:

2026-03-04 07:33 UTC, closed without merging