it's works
mate-academy/react_goods-selector-js pull request #765
Opened 2024-03-22 02:20 UTC by VadymBryvka

2024-03-22 07:32 UTC, etojeDenys requested changes
Якщо раптом щось із моїх коментарів тобі незрозуміло, то, будь ласка, не чекай і звертайся у чат з менторами або приходь на Q&A сесію. Обовʼязково з усім розберемось)

2024-03-22 07:32 UTC, etojeDenys commented on src/App.jsx
> +  const [selectedGood, setSelectedGood] = useState(true);
```suggestion

  const [selectedGood, setSelectedGood] = useState('Jam');
```

2024-03-22 07:32 UTC, etojeDenys commented on src/App.jsx
> +        {selectedGood ? `${good} is selected` : 'No goods selected'}
```suggestion
        {selectedGood ? `${selectedGood} is selected` : 'No goods selected'}
```

2024-03-22 07:32 UTC, etojeDenys commented on src/App.jsx
> +          {goods.map((x, index) => (
```suggestion
          {goods.map(good => (
```

2024-03-22 07:32 UTC, etojeDenys commented on src/App.jsx
> +                checkIndex === index && selectedGood
```suggestion
                selectedGood === good
```

2024-03-22 07:32 UTC, etojeDenys commented on src/App.jsx
> +    }
```suggestion
    setSelectedGood(selectedGood === currentGood ? null : currentGood)
```

2024-03-23 09:05 UTC, nazarmatsevych approved these changes
Good work!

2024-07-30 02:39 UTC, closed without merging