add solution
mate-academy/react_goods-selector-js pull request #85
Opened 2023-07-03 16:19 UTC by AndriiYelieva

[DEMO LINK](https://AndriiYelieva.github.io/react_goods-selector-js/)

2023-07-03 17:44 UTC, etojeDenys requested changes
I should have the ability to remove selected Good by clicking twice on the item

https://github.com/mate-academy/react_goods-selector-js/assets/70220667/2aca9643-c625-4852-bf25-8ea8d8938a3e

2023-07-03 17:44 UTC, etojeDenys commented on src/App.jsx
> +  const [selectGoods, setSelectGoods] = useState('Jam');
```suggestion
  const [selectedGood, setSelectedGood] = useState('Jam');
```

2023-07-03 17:44 UTC, etojeDenys commented on src/App.jsx
> +              >
don't forget about key prop

2023-07-04 10:00 UTC, IvanFesenko requested changes
Not fixed
![2023-07-04_12h59_41](https://github.com/mate-academy/react_goods-selector-js/assets/61904995/7eb2edd9-f1d0-4652-86bf-73a19dad959a)

https://github.com/mate-academy/react_goods-selector-js/assets/61904995/0397716c-c2ff-46fa-a35d-3e213679be12

2023-07-04 10:00 UTC, IvanFesenko commented on src/App.jsx
> +              >
Same here add key 
![2023-07-04_13h00_25](https://github.com/mate-academy/react_goods-selector-js/assets/61904995/eb0caa58-a01a-4460-b8f8-98b1319eeeac)

2023-07-04 10:38 UTC, IvanFesenko approved these changes

2024-09-12 11:12 UTC, closed without merging